# --------------------------------------------------------------
# |                                                            |
# |    Author: Sergio Boluda Fernandes                         |
# |    DevSecOps Engineer at BBVA Next Technologies            |
# |    If you detect any bug contact with sboludaf@outlook.es   |
# |                                                            |
# --------------------------------------------------------------

pool:
  vmImage: ubuntu-16.04

trigger:
  branches:
    include:
      - master
      - feature/
  paths:
    include:
      - 'Deployment/Templates By Service/'

steps:
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'Templates By Service'
    ArtifactName: 'IndividualResourceArtifact'
    publishLocation: 'Container'